### ISSUE TITLE
Implement range_cardinality method

### ISSUE THREAD

**Issue by lemire** [SalvatorePreviti/roaring-node#15]
See 
https://github.com/RoaringBitmap/CRoaring/pull/188

**Comment by SalvatorePreviti** [comment]
@lemire will implement soon, however, I would need a new version of https://github.com/lemire/CRoaringUnityBuild - roaring-node depends on it (it is easier to compile and to share as npm package)

**Comment by lemire** [comment]
Done.

**Comment by SalvatorePreviti** [comment]
Closed in v1.0.3
Implemented also the new removeMany
