### ISSUE TITLE
Serialization should in portable mode by default...

### ISSUE THREAD

**Issue by lemire** [SalvatorePreviti/roaring-node#23]
For users who seek interoperability with Java, having a non-portable output format by default can be confusing... See

https://github.com/RoaringBitmap/RoaringBitmap/issues/367

**Comment by SalvatorePreviti** [comment]
Yes, unfortunately I didn't think about this when I wrote the serialize method. I fear that changing it now could break code of whoever used this library to serialize and deserialize, like I did.
One option would be to deprecate the serialize method and raise a warning when used the first time in an app and introduce two new methods with different names for portable and the more optimised non portable version.
Any other ideas?

**Comment by SalvatorePreviti** [comment]
Or, simpler, raise the warning if the Boolean parameter is not provided, and make it required in the typescript definition

**Comment by lemire** [comment]
I agree that changing it silently now would break systems. Let us not do that.

If you make it required, what happens if someone fails to provide the parameter... will their code still run or will it break? Then that's not nice.

The ideal scenario would be a warning with an explanation one someone either fails to pass a parameter of fails to require the "portable" mode.

**Comment by SalvatorePreviti** [comment]
Yes the idea Is using the default NodeJS warning system, used already for deprecation warnings, so code will not break. https://nodejs.org/api/process.html#process_process_emitwarning_warning_options

I will try to do it this week when I have some time :)

**Comment by SalvatorePreviti** [comment]
Probably would be better to define `serialize(format: "portable" | "croaring")` using a string instead of a boolean so this is clearer and can be extended in the future. Ideas for the non portable name are welcome.

**Comment by rajcspsg** [comment]
@SalvatorePreviti - I'm not a nodejs developer. we have one application writing to DB and another reading from it. So better add note about portable flag in the read me.

**Comment by SalvatorePreviti** [comment]
The note is already there, started to change the code but didn't have much time. `If false (default), optimized C/C++ format is used. If true, Java and Go portable format is used.`

**Comment by SalvatorePreviti** [comment]
Versione 1.1.7 just released enforces the user to specify in all serialization method a boolean flag that indicates if is portable or not. The flag is not optional and functions will throw an error if the flag is not passed.
Is a breaking change but is easy to fix in who uses this library right now and avoid the confusion discussed here.
