### ISSUE TITLE
Add support for roaring_bitmap_add_range

### ISSUE THREAD

**Issue by lemire** [SalvatorePreviti/roaring-node#3]
We have a new function that can quickly add a range of values.

https://github.com/RoaringBitmap/CRoaring/pull/148

**Comment by SalvatorePreviti** [comment]
Hi, I was implementing it but noticed a different behaviour between roaring_bitmap_add_range and roaring_bitmap_flip_range.

roaring_bitmap_add_range(bitmap, 10, 12) makes a bitmap [10, 11, 12] - first and last inclusive
roaring_bitmap_flip_range(bitmap, 10, 12) makes a bitmap [10, 11] - first inclusive, last exclusive

This different behaviour is intended?

**Comment by lemire** [comment]
It is not.

**Comment by SalvatorePreviti** [comment]
I see, is it a bug in the C code? Shall I wait the next release?

**Comment by SalvatorePreviti** [comment]
I see, roaring_bitmap_flip_inplace accepts uint64_t values so is possible to specify (2^32)+1. Shall roaring_bitmap_add_range be the same?

**Comment by lemire** [comment]
I am going to issue a new release so that add_range is consistent (taking 64-bit values).

**Comment by SalvatorePreviti** [comment]
About contains_range, will it be with 64 bit values too?

**Comment by SalvatorePreviti** [comment]
roaring_bitmap_contains_range is with 64 bit values already, will implement that.

**Comment by SalvatorePreviti** [comment]
Found a bug in my fliprange, fixing it

**Comment by SalvatorePreviti** [comment]
I think there is another bug.
These causes an infinite loop (I guess)

  roaring_bitmap_flip_inplace(&self->roaring, 4294967295, 4294967296);
  roaring_bitmap_flip_inplace(&self->roaring, 4294967294, 4294967296);
  roaring_bitmap_flip_inplace(&self->roaring, 4294967294, 4294967297);

**Comment by SalvatorePreviti** [comment]
Ah, is the compiler I guess. Sorry.
This seems to work.

  roaring_bitmap_flip_inplace(&self->roaring, 4294967295ULL, 4294967296ULL);
  roaring_bitmap_flip_inplace(&self->roaring, 4294967294ULL, 4294967296ULL);
  roaring_bitmap_flip_inplace(&self->roaring, 4294967294ULL, 4294967297ULL);

**Comment by SalvatorePreviti** [comment]
Uhm, sorry again, there is something strange with bitmap_flip_inplace + iterator.
It seems that flipping just the last value (0xFFFFFFFF) on an empty bitmap from 0 to 1 breaks the iterator.
It does not happen when using roaring_bitmap_add(0xFFFFFFFF).

I will do more test later and open an issue with the complete source code.
Maybe you know what could be the reason for this behaviour?

roaring_bitmap_flip_inplace(bitmap, 4294967295ULL, 4294967296ULL); // OK
roaring_bitmap_get_cardinality(bitmap); // OK, is 1
roaring_bitmap_contains(bitmap, 0xFFFFFFFF); // OK is true
roaring_bitmap_contains(bitmap, 0); // OK is false

roaring_uint32_iterator_t iterator;
roaring_init_iterator(bitmap, &iterator);

roaring_advance_uint32_iterator(&iterator); // OK, is true
iterator.current_value // OK, is 0xFFFFFFFF
iterator.has_value // OK, is true

roaring_advance_uint32_iterator(&iterator); // NOT OK, is true
iterator.current_value // NOT OK, is 0
iterator.has_value // NOT OK, is true

roaring_advance_uint32_iterator(&iterator); // NOT OK, is true
iterator.current_value // NOT OK, is 1
iterator.has_value // NOT OK, is true

roaring_advance_uint32_iterator(&iterator); // NOT OK, is true
iterator.current_value // NOT OK, is 2
iterator.has_value // NOT OK, is true

.... and so on

**Comment by lemire** [comment]
I'll investigate.

**Comment by lemire** [comment]
Yes. Something is strange.

**Comment by SalvatorePreviti** [comment]
Unfortunately, it seems there is an issue with roaring_bitmap_contains_range too with the end.

roaring_bitmap_add(&self->roaring, 4294967296)
roaring_bitmap_contains_range(&self->roaring, 4294967296, 4294967297) // NOT OK, is false

**Comment by lemire** [comment]
Right. These are new functions. I'm testing them.

**Comment by lemire** [comment]
Please update to v0.2.47 

It should be fine now. At least, all the problems you reported are now tested for.

**Comment by SalvatorePreviti** [comment]
just saw it! It works. Amazing :)

If you want, have a look at https://github.com/SalvatorePreviti/roaring-node/pull/4
I will merge tomorrow and release a new version.

**Comment by SalvatorePreviti** [comment]
Included in roaring v0.2.6, roaring-aws v0.2.8
