### ISSUE TITLE
Should inform V8's GC about externally allocated memory

### ISSUE THREAD

**Issue by papandreou** [SalvatorePreviti/roaring-node#37]
Hi!

An application I'm working on is a heavy user of this library and big bitmaps -- thanks a lot! I'm experiencing some strange GC behavior that might be explained by roaring-node not letting V8 know about the memory that has been `malloc`ed outside the JavaScript heap using [`isolate->AdjustAmountOfExternalAllocatedMemory(delta)`](https://v8docs.nodesource.com/node-16.0/d5/dda/classv8_1_1_isolate.html#ae1a59cac60409d3922582c4af675473e). In my case this seems to cause the garbage collector to kick in too late when the process is out of memory, causing very long GC pauses.

I learned about this method from reading some of node.js' own C++ code, eg. [the zlib wrapper](https://github.com/nodejs/node/blob/879ff775d039aa9b1becd548a99a7e19937521f5/src/node_zlib.cc#L506-L515)

Just to test it, I've tried scattering in some super naive and wrong calls:

```diff
diff --git a/src/cpp/RoaringBitmap32.cpp b/src/cpp/RoaringBitmap32.cpp
index 3005806..f2948aa 100644
--- a/src/cpp/RoaringBitmap32.cpp
+++ b/src/cpp/RoaringBitmap32.cpp
@@ -169,6 +169,8 @@ RoaringBitmap32::~RoaringBitmap32() {
 
 void RoaringBitmap32::WeakCallback(v8::WeakCallbackInfo<RoaringBitmap32> const & info) {
   RoaringBitmap32 * p = info.GetParameter();
+  v8::Isolate * isolate = info.GetIsolate();
+  isolate->AdjustAmountOfExternalAllocatedMemory(-10000000);
   delete p;
 }
 
@@ -200,6 +202,7 @@ void RoaringBitmap32::New(const v8::FunctionCallbackInfo<v8::Value> & info) {
   if (!instance || !instance->roaring) {
     return v8utils::throwError(isolate, "RoaringBitmap32::ctor - failed to create native RoaringBitmap32 instance");
   }
+  isolate->AdjustAmountOfExternalAllocatedMemory(10000000);
 
   holder->SetAlignedPointerInInternalField(0, instance);
   instance->persistent.Reset(isolate, holder);
```

When I run a small script that keeps creating garbage `RoaringBitmap32` instances (with `node --trace-gc`), the above makes V8 run mark-sweep garbage collections way more often. I know this doesn't really prove anything, but at least hints that it's needed here.

What do you think?

**Comment by SalvatorePreviti** [comment]
Yeah I thought about it and the reasoning makes sense. However is going to be hard to understand how much a roaring bitmap consumes. An empty roaring bitmap consumes few bytes, and the operations on a bitmap might change its size dramatically, in both directions. One option is of course run your node application with --gc and manually call collect when needed until I don't think better about this, and run some tests to be sure there is not a leak in the library somewhere.

**Comment by papandreou** [comment]
Thanks -- and absolutely! Just say the word.

**Comment by SalvatorePreviti** [comment]
I just released a new version of the package, https://github.com/SalvatorePreviti/roaring-node/releases/tag/v1.2.0 
Computing exactly how much a bitmap consumes is expensive and reduces speed if run for every possible operation.
For this reason, I did decide to add 4096 bytes to AdjustAmountOfExternalAllocatedMemory at every RoaringBitmap32 creation and execute a better estimation every time runOptimize or shrinkToFit are called or after serialization and deserialization.

**Comment by papandreou** [comment]
@SalvatorePreviti, thanks a lot for doing that, it sounds like a good compromise!

I will take it for a spin 🏎️
