### ISSUE TITLE
nodejs 20 is out and it  needs c++17

### ISSUE THREAD

**Issue by wuhanck** [SalvatorePreviti/roaring-node#50]
roaring-node build failed. I guess it is c++17 issue

**Comment by SalvatorePreviti** [comment]
Was already working on it, it needs both fixes in the code, abandon prebuild and move to node-pre-gyp, kill support for node 8 and 10, change the build flow and CI, and the branch I am working on is https://github.com/SalvatorePreviti/roaring-node/tree/deploy-alpha

**Comment by SalvatorePreviti** [comment]
Just released version 2.0.0 that drops support for node 8 and 10 and adds support to node 20
